# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: gcr.io/jx-mar19/jx-app-fossa
  tag: 1.0.3
apiKey: "{{ .Values.apiKey }}"
verifyonpreview: "{{ .Values.verifyonpreview }}"
verifyonrelease: "{{ .Values.verifyonrelease }}"
