apiVersion: jenkins.io/v1
kind: App
metadata:
    name: {{ template "fullname" . }}
    labels:
        jenkins.io/app-type: pipeline-extension
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
    pipelineExtension:
        name: FOSSA
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: /jx-app-fossa.sh
        args:
          - "k={{ .Values.apiKey }}"
          - "p={{ .Values.verifyonpreview }}"
          - "r={{ .Values.verifyonrelease }}"
